# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
  schedule:
    - cron: '00 21 * * 4' # 4:00pm EDT, Thursday

env:
  IMAGE_NAME: gcr.io/fulfil-web/fulfil_dc_api

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Fulfil0518'
      - name: Change to non-node tmp dir
        run: mkdir /tmp/semrel
      - name: Install dependencies
        working-directory: /tmp/semrel
        run: npm install --loglevel=info --no-save @semantic-release/exec @semantic-release/changelog @semantic-release/git @semantic-release/github @openapitools/openapi-generator-cli@2.13.1
      - name: Move semantic-release to CWD
        run: mv /tmp/semrel/node_modules .
      - name: Login to GCP Registry (Production)
        uses: Fulfil0518/gcp-registry-login-action@v1
        env:
          CLOUD_PROD_SA: ${{ secrets.CLOUD_PROD_SA }}
        with:
          endpoint: ${{ env.IMAGE_NAME }}
          service_key: ${{ env.CLOUD_PROD_SA }}
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN  }}
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
          NPM_GITHUB_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
          SEMANTIC_RELEASE: '1'
          NODE_AUTH_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}
        run:
          make release
